services:
  monodb:
    image: "mongo"
    ports:
      - 27017:27017
    environment:
    - MONGO_INTIDB_ROOT_USERNAME=admin
    - MONGO_INTIDB_ROOT_PASSWORD=password
  monodbono-express:
    image: "mongo-express"
    ports:
      - 8080:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERMAN=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=monodb


    